MediaBazaarWebsite/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MediaBazaarWebsite
{
    public class LoginController
    {
        [Required, BindProperty]
        public string Username { get; set; }
        [Required, BindProperty, DataType(DataType.Password)]
        public string Password { get; set; }

        public LoginController() { }
    }
}

MediaBazaarWebsite/Controllers/ProfileController.cs
using MediaBazaarClassLibrary;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MediaBazaarWebsite
{
    public class ProfileController
    {
        [Required, BindProperty, DataType(DataType.Date)]
        public DateTime BirthDate { get; set; }
        [Required, BindProperty]
        public Gender Gender { get; set; }
        [Required, BindProperty]
        public string FirstName { get; set; }
        [Required, BindProperty]
        public string LastName { get; set; }
        [Required, BindProperty, DataType(DataType.Password)]
        public string Password { get; set; }
        [Required, BindProperty]
        public string Phone { get; set; }
        [Required, BindProperty]
        public string Email { get; set; }
        [Required, BindProperty]
        public string Postal { get; set; }
        [Required, BindProperty]
        public string ContactName { get; set; }
        [Required, BindProperty]
        public string ContactPhone { get; set; }

        public ProfileController() { }
    }
}

MediaBazaarWebsite/Pages/AccessDenied.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Website.Pages
{
    public class AccessDeniedModel : PageModel
    {

    }
}

MediaBazaarWebsite/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MediaBazaarWebsite.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

MediaBazaarWebsite/Pages/Index.cshtml.cs
using MediaBazaarClassLibrary;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MediaBazaarWebsite
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public ShiftManager shiftManager;
        [BindProperty]
        public DateController DateModel { get; set; }

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;

            DateTime dateTime = DateTime.Today;
            this.DateModel = new DateController(dateTime);

            this.shiftManager = new ShiftManager(new ShiftSQL());
        }

        public void OnGet(string date)
        {
            if (date != null)
            {
                this.DateModel = new DateController(DateTime.Parse(date));
            }
        }

        public IActionResult OnPostNext(string currentDate)
        {
            return RedirectToPage("Index", new
            {
                date = currentDate
            });
        }

        public IActionResult OnPostPrevious(string currentDate)
        {
            return RedirectToPage("Index", new
            {
                date = currentDate
            });
        }
    }
}

MediaBazaarWebsite/Pages/LogOut.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Website.Pages
{
    public class LogOutModel : PageModel
    {
        public IActionResult OnGet()
        {
            // @WAD:   to logout call the method HttpContext.SignOutAsync()
            HttpContext.SignOutAsync();

            return RedirectToPage("/Login");
        }
    }
}

MediaBazaarWebsite/Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using MediaBazaarClassLibrary;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MediaBazaarWebsite
{
    public class LoginModel : PageModel
    {
        public LoginManager LoginManager { get; set; }

        [BindProperty]
        public LoginController Login { get; set; }

        public LoginModel()
        {
            this.LoginManager = new LoginManager(new LoginWebsiteSQL());
        }

        public IActionResult OnPost(string? returnUrl)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    Employee employee = LoginManager.Login(new Employee(this.Login.Username, this.Login.Password));

                    if (employee != null)
                    {
                        List<Claim> claims = new List<Claim>();
                        claims.Add(new Claim(ClaimTypes.Name, employee.Username));
                        claims.Add(new Claim("id", employee.ID.ToString()));

                        var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                        HttpContext.SignInAsync(new ClaimsPrincipal(claimsIdentity));

                        // Url.IsLocalUrl is to prevent Open Redirect Attacks
                        // See 'What is an Open Redirection Attack?' @ https://docs.microsoft.com/en-us/aspnet/mvc/overview/security/preventing-open-redirection-attacks)
                        if (!String.IsNullOrWhiteSpace(returnUrl) && Url.IsLocalUrl(returnUrl))
                        {
                            return Redirect(returnUrl);
                        }

                        return RedirectToPage("Index");
                    }
                }

                ModelState.AddModelError("InvalidCredentials", "Either the supplied username/password is invalid or you have been blocked");
                return Page();
            }
            catch
            {
                return Page();
            }
        }
    }
}

MediaBazaarWebsite/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MediaBazaarWebsite.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

MediaBazaarWebsite/Pages/Profile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using MediaBazaarClassLibrary;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MediaBazaarWebsite
{
    [Authorize]
    public class ProfileModel : PageModel
    {
        public EmployeeManager employeeManager = new EmployeeManager(new EmployeeSQL());
        [BindProperty]
        public ProfileController ProfileController { get; set; }

        public void OnGet ()
        {
            this.ProfileController = new ProfileController();

            Employee employee = this.employeeManager.Get(new EmployeeGetByID(Convert.ToInt32(User.FindFirst("id").Value)));
            this.ProfileController.Gender = employee.Gender;
            this.ProfileController.FirstName = employee.FirstName;
            this.ProfileController.LastName = employee.LastName;
            this.ProfileController.Password = employee.Password;
            this.ProfileController.Phone = employee.Phone;
            this.ProfileController.Email = employee.Email;
            this.ProfileController.Postal = employee.Postal;
            this.ProfileController.ContactName = employee.ContactName;
            this.ProfileController.ContactPhone = employee.ContactPhone;
            this.ProfileController.BirthDate = employee.BirthDate;
        }

        public IActionResult OnPost ()
        {
            try
            {
                Employee employee = this.employeeManager.Get(new EmployeeGetByID(Convert.ToInt32(User.FindFirst("id").Value)));

                this.employeeManager.Update(new EmployeeGetEdit(employee, new Employee(employee.ID,
                    employee.BSN,
                    employee.WorkingHours,
                    employee.Position,
                    employee.Salary,
                    employee.IsActive,
                    this.ProfileController.BirthDate,
                    employee.HireDate,
                    this.ProfileController.Gender,
                    this.ProfileController.FirstName,
                    this.ProfileController.LastName,
                    this.ProfileController.Password,
                    this.ProfileController.Phone,
                    this.ProfileController.Email,
                    this.ProfileController.Postal,
                    this.ProfileController.ContactName,
                    this.ProfileController.ContactPhone
                    )));

                return Page();
            }
            catch
            {
                return RedirectToPage("Profile");
            }
        }
    }
}

MediaBazaarWebsite/Pages/AccessDenied.cshtml
@page
@model Website.Pages.AccessDeniedModel
@{
    ViewData["Title"] = "Access Denied";
}

<div class="text-center">
    <h1 class="display-4">Access Denied</h1>
    <p>
        You do not have rights to access this page!
    </p>
</div>

MediaBazaarWebsite/Pages/Index.cshtml
@page "{date?}"
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
    <form method="post" asp-page="index" asp-page-handler="previous">
        <input type="hidden" name="currentDate" value="@Model.DateModel.Date.AddDays(-7).ToString()" />
        <input class="left" type="submit" value="<">
    </form>
    <form method="post" asp-page="index" asp-page-handler="next">
        <input type="hidden" name="currentDate" value="@Model.DateModel.Date.AddDays(7).ToString()" />
        <input class="right" type="submit" value=">">
    </form>
<h3>Calendar</h3>
<div class="container">
    <table id="monthlyCalendar">
        <thead class="calendarDay">
            <tr>
                <td class="calendarDay">Mo</td>
                <td class="calendarDay">Tu</td>
                <td class="calendarDay">We</td>
                <td class="calendarDay">Th</td>
                <td class="calendarDay">Fr</td>
            </tr>
        </thead>
        <tbody>
            <tr>
                @for (int i = 1; i <= 5; i++)
                {
                    <td class="calendarDate">
                        @if (DateTime.Today == Model.DateModel.WeekStart)
                        {
                            <div class="today">@Model.DateModel.WeekStart.ToString("dd/MM/yy")</div>
                        }
                        else
                        {
                            <div class="day">@Model.DateModel.WeekStart.ToString("dd/MM/yy")</div>
                        }

                        @if (Model.shiftManager.Get(new ShiftFilterEmployeeDateTime(Convert.ToInt32(User.FindFirst("id").Value), Model.DateModel.Date, Time.Morning)) != null)
                        {
                            <div class="morning">09:00 - 12:00</div>
                        }
                        else
                        {
                            <div class="standIn"></div>
                        }
                        @if (Model.shiftManager.Get(new ShiftFilterEmployeeDateTime(Convert.ToInt32(User.FindFirst("id").Value), Model.DateModel.Date, Time.Afternoon)) != null)
                        {
                            <div class="afternoon">12:00 - 15:00</div>
                        }
                        else
                        {
                            <div class="standIn"></div>
                        }
                        @if (Model.shiftManager.Get(new ShiftFilterEmployeeDateTime(Convert.ToInt32(User.FindFirst("id").Value), Model.DateModel.Date, Time.Evening)) != null)
                        {
                            <div class="evening">15:00 - 18:00</div>
                        }
                        else
                        {
                            <div class="standIn"></div>
                        }
                    </td>

                    Model.DateModel.AddDay();
                }
            </tr>
        </tbody>
    </table>
</div>

MediaBazaarWebsite/Pages/LogOut.cshtml
@page
@model Website.Pages.LogOutModel
@{
    ViewData["Title"] = "Logout";
}

MediaBazaarWebsite/Pages/Login.cshtml
@page
@model LoginModel
@{
    ViewData["Title"] = "Login";
}

<h1>Login</h1>
<div class="input-form">
    <form method="post">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="@Model.Login.Username"></label><br />
            <input asp-for="@Model.Login.Username" class="form-control">
        </div>
        <div class="form-group">
            <label asp-for="@Model.Login.Password"></label><br />
            <input asp-for="@Model.Login.Password" class="form-control">
        </div>
        <div class="form-group">
            <button type="submit" class="post-button">Log in</button>
        </div>
    </form>
</div>

MediaBazaarWebsite/Pages/Profile.cshtml
@page "{employeeID?}"
@model ProfileModel
@{
    ViewData["Title"] = "Profile";
}

<div class="input-form">
    <form method="post">
        <div id="grid-profile">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="profile-username">
                <div class="form-group">
                    <label asp-for="@Model.employeeManager.Get(new EmployeeGetByID(Convert.ToInt32(User.FindFirst("id").Value))).Username"></label><br />
                    <div class="username">@Model.employeeManager.Get(new EmployeeGetByID(Convert.ToInt32(User.FindFirst("id").Value))).Username</div>
                </div>
            </div>
            <div class="profile-password">
                <div class="form-group">
                    <label asp-for="@Model.ProfileController.Password"></label><br />
                    <input asp-for="@Model.ProfileController.Password" class="form-control">
                </div>
            </div>
            <div class="profile-firstname">
                <div class="form-group">
                    <label asp-for="@Model.ProfileController.FirstName"></label><br />
                    <input asp-for="@Model.ProfileController.FirstName" class="form-control">
                </div>
            </div>
            <div class="profile-lastname">
                <div class="form-group">
                    <label asp-for="@Model.ProfileController.LastName"></label><br />
                    <input asp-for="@Model.ProfileController.LastName" class="form-control">
                </div>
            </div>
            <div class="profile-gender">
                <div class="form-group">
                    <label asp-for="@Model.ProfileController.Gender"></label><br />
                    <select class="form-dropdown" asp-for="@Model.ProfileController.Gender" asp-items="Html.GetEnumSelectList<Gender>()">
                    </select>
                </div>
            </div>
            <div class="profile-birthdate">
                <div class="form-group">
                    <label asp-for="@Model.ProfileController.BirthDate"></label><br />
                    <input asp-for="@Model.ProfileController.BirthDate" class="form-control">
                </div>
            </div>
            <div class="profile-phone">
                <div class="form-group">
                    <label asp-for="@Model.ProfileController.Phone"></label><br />
                    <input asp-for="@Model.ProfileController.Phone" class="form-control">
                </div>
            </div>
            <div class="profile-email">
                <div class="form-group">
                    <label asp-for="@Model.ProfileController.Email"></label><br />
                    <input asp-for="@Model.ProfileController.Email" class="form-control">
                </div>
            </div>
            <div class="profile-postal">
                <div class="form-group">
                    <label asp-for="@Model.ProfileController.Postal"></label><br />
                    <input asp-for="@Model.ProfileController.Postal" class="form-control">
                </div>
            </div>
            <div class="profile-contactname">
                <div class="form-group">
                    <label asp-for="@Model.ProfileController.ContactName"></label><br />
                    <input asp-for="@Model.ProfileController.ContactName" class="form-control">
                </div>
            </div>
            <div class="profile-contactphone">
                <div class="form-group">
                    <label asp-for="@Model.ProfileController.ContactPhone"></label><br />
                    <input asp-for="@Model.ProfileController.ContactPhone" class="form-control">
                </div>
            </div>
        </div>
        <div class="form-group">
            <button type="submit" class="post-button">Update</button>
        </div>
    </form>
</div>